/*
 * bit_manipulation.h
 *
 * Created: 4/3/2014 10:23:28 AM
 *  Author: razius
 */ 


#ifndef BIT_MANIPULATION_H_
#define BIT_MANIPULATION_H_

    #define SET_BIT(ADDRESS, BIT_POSITION) (ADDRESS |= _BV(BIT_POSITION))
    #define CLEAR_BIT(ADDRESS, BIT_POSITION) (ADDRESS &= ~_BV(BIT_POSITION))
    #define TOGGLE_BIT(ADDRESS, BIT_POSITION) (ADDRESS ^= _BV(BIT_POSITION))
    #define WRITE_BIT(ADDRESS, BIT_POSITION, BIT_VALUE) (BIT_VALUE ? SET_BIT(ADDRESS, BIT_POSITION) : CLEAR_BIT(ADDRESS, BIT_POSITION))
    
    #define CLOCK_PIN(ADDRESS, BIT_POSITION) (SET_BIT(ADDRESS,BIT_POSITION), CLEAR_BIT(ADDRESS,BIT_POSITION))

#endif /* BIT_MANIPULATION_H_ */